name: injecatble_example
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  injectable: ^2.3.2
  get_it: ^7.6.7
  hooked_bloc: ^1.5.0
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
